Region:
  points_per_region: 64
  region_threshold: 0
  region_size: 0.02
  clip_bound: ""
  # scale_augmentation_bound: [0.9, 1.1]
  rotation_augmentation_bound: [-1/64, 1/64, -1/64, 1/64, -1, 1]
  translation_augmentation_ratio_bound: [-0.2, 0.2, -0.2, 0.2, 0, 0]

grid_size: 0.002
use_rgb: True
use_normal: False
# use_whole: False

only_test: False

train:
  data_dir: data/synthetic_tabletop
  num_workers: 12
  batch_size: 1
  pin_memory: True

val:
  data_dir: data/synthetic_tabletop
  num_workers: 8
  batch_size: 1
  pin_memory: True

test:
  data_dir: data/synthetic_tabletop
  num_workers: 8
  batch_size: 1
  pin_memory: True
