project: Spatial3D

num_epochs: 100
clip_grad_max_norm: 0.1

Optimizer:
  name: AdamW
  kwargs:
    lr: !!float 1e-4
    betas: [0.9, 0.999]
    weight_decay: !!float 1e-3

Scheduler:
  name: StepLR
  kwargs:
    CosineAnnealingWarmUpRestarts_jskim:
      T_0: 150
      T_mult: 1
      eta_max: 0.1
      T_up: 10
      gamma: 0.5
    CosineAnnealingWarmUpRestarts_katsura:
      first_cycle_steps : 100
      cycle_mult : 1
      max_lr : 0.001
      min_lr : 0.00000001
      warmup_steps : 0
      gamma : 1
      last_epoch : -1
    StepLR:
      step_size: 150

loss_type: [BCEWithLogitsLoss, BCETverskyLoss]
imbalance_weight: 3
label_smoothing_eps: 0.1

freeze_pretrain: True
text_encoder_in_CPU: True

distributed: True
train_gpu: [0,1]

print_freq: 5

output_dir: output
ckpt_dir: output/ckpt
heatmap_dir: output/heatmaps

Resume:
  resume_training: False
  resume_epoch: 0
