rng_seed: 42

base_dir: output
model_config_path: cfg/model/model.yaml
dataset_config_path: cfg/data/dataset.yaml
instructions_config_path: cfg/data/instruction.yaml

name: SegPoint
note: default

tasks: ["SemanticSegmentation"]
task_type: ["specific", "all_categories"]

mode: train
naming_keywords: [time]   # choose keywords to feature the exp run dir

num_gpu: 3

logger:
  name: wandb
  entity: kiyoungkwon-seoul-national-university

pretrained_ckpt_path: ""


train:
  gradient_accumulation_steps: 5
  grad_norm: 5.0
  batch_size: 2
  num_workers: 5
  pin_memory: True
  epochs: 100

  optim:
    name: AdamW
    args:
      lr: 5e-5
      betas: [0.9, 0.999]
      weight_decay: 0.05
  schedule:
    name: linear_warmup_cosine_decay
    args:
      warmup_steps: 150

eval:
  val_interval: 3
  num_batch_val: 1e4
  


val:
  batch_size: 1
  num_workers: 2
  pin_memory: True

test:
  batch_size: 1 
  num_workers: 2
  pin_memory: True